torchrun --nproc_per_node 2 \
	-m FlagEmbedding.finetune.reranker.encoder_only.base \
	--model_name_or_path AITeamVN/Vietnamese_Reranker \
    --cache_dir ./cache_zalo/model \
    --train_data ./pair_data_zalo/rerank_data_top20.jsonl \
    --cache_path ./cache_zalo/data \
    --train_group_size 8 \
    --query_max_len 256 \
    --passage_max_len 2048 \
    --pad_to_multiple_of 8 \
    --knowledge_distillation False \
	--output_dir ./zalo-legal-reranker \
    --overwrite_output_dir \
    --learning_rate 6e-5 \
    --fp16 \
    --num_train_epochs 4 \
    --per_device_train_batch_size 6 \
    --gradient_accumulation_steps 1 \
    --dataloader_drop_last True \
    --max_grad_norm 5.0 \
    --warmup_ratio 0.1 \
    --gradient_checkpointing \
    --weight_decay 0.01 \
    --deepspeed ./ds_stage0.json \
    --logging_steps 50 \
    --save_steps 1000 \
    --hub_token  \
    --push_to_hub \
    --hub_model_id phonghoccode/ALQAC_2025_Reranker_top20_zalo
torchrun --nproc_per_node 2 \
	-m FlagEmbedding.finetune.reranker.encoder_only.base \
	--model_name_or_path phonghoccode/ALQAC_2025_Reranker_top20_zalo \
    --cache_dir ./cache/model \
    --train_data ./pair_data/rerank_data_top20.jsonl \
    --cache_path ./cache/data \
    --train_group_size 8 \
    --query_max_len 256 \
    --passage_max_len 2048 \
    --pad_to_multiple_of 8 \
    --knowledge_distillation False \
	--output_dir ./legal-reranker \
    --overwrite_output_dir \
    --learning_rate 6e-5 \
    --fp16 \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --dataloader_drop_last True \
    --warmup_ratio 0.1 \
    --gradient_checkpointing \
    --weight_decay 0.01 \
    --deepspeed ./ds_stage0.json \
    --logging_steps 50 \
    --save_steps 1000 \
    --hub_token  \
    --push_to_hub \
    --hub_model_id phonghoccode/ALQAC_2025_Reranker_top20_final